version: "3"

services:
  nginx:
    build: ./nginxapp
    restart: always
    volumes:
      - ./nginxapp/www/:/home/web/www
    ports:
      - "80:80"
      - "443:443"

  postgres:
    image: postgres:13.3
    restart: unless-stopped
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./dbdata:/var/lib/postgresql/data
      - ./dbroot:/root
      - ./dbroot/init.sql:/docker-entrypoint-initdb.d/db.sql
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d postgres'"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: ./aspapp
    depends_on:
      - nginx
      - postgres
    # command: sh -c "dotnet WebApplicationTestDocker.dll"
    # volumes:
    #   - ./apsapp/code:/root